### ISSUE TITLE
support `sticky`?

### ISSUE THREAD

**Issue by njzjz** [Jamling/hexo-generator-index2#10]
See https://github.com/hexojs/hexo-generator-index/pull/51. It's nice if `hexo-generator-index2` can also have this feature.

**Comment by airinghost** [comment]
```yaml
index2_include_index: true
index2_generator:
  - layout: 'index'
    path: ''
    index: true
    per_page: 10
    order_by: -sticky
```
Then set `sticky: [numbers]` in Front-matter for every post. This works on my devices.
