### ISSUE TITLE
怎么设置首页只显示某个文件夹下的文章

### ISSUE THREAD

**Issue by mutouh** [Jamling/hexo-generator-index2#6]
使用hexo-generator-index2想要设置首页只显示某个路径下的文章，试了好几种写法都无效。
```
index2_generator:
  per_page: 10
  order_by: -date # 按发布时间排序
  include:
    - path /source/_post/main/  # not working
```
某度无果，请问path应该怎么写？

**Comment by mutouh** [comment]
已解决。如果想要在首页展示的文章在/source/_posts/main/下，则
```
index2_generator:
  per_page: 10
  order_by: -date # 按发布时间排序
  include:
    - path main
```
